CREATE TABLE OrderElement (elementId VARCHAR(50) NOT NULL, name VARCHAR(200) NOT NULL, objectId DOUBLE NOT NULL, type VARCHAR(100) NOT NULL)
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL,  PRIMARY KEY(TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ()
;

