package net.form105.rm.base.server.auto;

/** Class _OrderElement was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _OrderElement extends org.apache.cayenne.CayenneDataObject {

    public static final String ELEMENT_ID_PROPERTY = "elementId";
    public static final String NAME_PROPERTY = "name";
    public static final String TYPE_PROPERTY = "type";

    public static final String OBJECT_ID_PK_COLUMN = "objectId";

    public void setElementId(String elementId) {
        writeProperty("elementId", elementId);
    }
    public String getElementId() {
        return (String)readProperty("elementId");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
}
