package net.form105.rm.base.message;


/**
 * Register a notification for incoming messages. The messages should be forwarded to this implementation.
 * The registry itself should have notification entries. The keys are used to register the notification 
 * by a hashCode generated by key1 and key2. Therefor a {@link KeyPair} could be used.
 * @author heiko
 *
 */
public interface IMessageNotificationRegistry {

	public abstract void register(String key1, String key2, IMessageNotification notification);

	public abstract void unregister(String key1, String key2);

	public abstract IMessageNotification getNotification(String key1, String key2);

}