CREATE TABLE AgentObject (ELEMENT_ID VARCHAR(50) NULL, NAME VARCHAR(100) NULL, OBJECT_ID INTEGER NOT NULL, TYPE VARCHAR(50) NULL, PRIMARY KEY (OBJECT_ID))
;

CREATE TABLE AbstractParameter (ELEMENT_ID VARCHAR(50) NULL, NAME VARCHAR(100) NULL, OBJECT_ID INTEGER NOT NULL, PARENT_ID VARCHAR(50) NULL, PRIMARY KEY (OBJECT_ID))
;

