package net.form105.db.cayenne.mapping.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Contact was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contact extends CayenneDataObject {

    public static final String ADDRESS1_PROPERTY = "address1";
    public static final String ADDRESS2_PROPERTY = "address2";
    public static final String CITY_PROPERTY = "city";
    public static final String COMPANY_NAME_PROPERTY = "companyName";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String ID_PROPERTY = "id";
    public static final String IS_DEFAULT_PROPERTY = "isDefault";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String NOTIFICATION_EMAIL_PROPERTY = "notificationEmail";
    public static final String PHONE_PROPERTY = "phone";
    public static final String STATE_PROPERTY = "state";
    public static final String TYPE_RESERVED_PROPERTY = "typeReserved";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String ZIP_PROPERTY = "zip";

    public static final String ID_PK_COLUMN = "id";

    public void setAddress1(String address1) {
        writeProperty("address1", address1);
    }
    public String getAddress1() {
        return (String)readProperty("address1");
    }

    public void setAddress2(String address2) {
        writeProperty("address2", address2);
    }
    public String getAddress2() {
        return (String)readProperty("address2");
    }

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setCompanyName(String companyName) {
        writeProperty("companyName", companyName);
    }
    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setIsDefault(String isDefault) {
        writeProperty("isDefault", isDefault);
    }
    public String getIsDefault() {
        return (String)readProperty("isDefault");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setNotificationEmail(String notificationEmail) {
        writeProperty("notificationEmail", notificationEmail);
    }
    public String getNotificationEmail() {
        return (String)readProperty("notificationEmail");
    }

    public void setPhone(String phone) {
        writeProperty("phone", phone);
    }
    public String getPhone() {
        return (String)readProperty("phone");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setTypeReserved(String typeReserved) {
        writeProperty("typeReserved", typeReserved);
    }
    public String getTypeReserved() {
        return (String)readProperty("typeReserved");
    }

    public void setUserId(Double userId) {
        writeProperty("userId", userId);
    }
    public Double getUserId() {
        return (Double)readProperty("userId");
    }

    public void setZip(String zip) {
        writeProperty("zip", zip);
    }
    public String getZip() {
        return (String)readProperty("zip");
    }

}
