package net.form105.db.cayenne.mapping.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MaterialFile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MaterialFile extends CayenneDataObject {

    public static final String FILE_PROPERTY = "file";
    public static final String ID_PROPERTY = "id";
    public static final String MATERIAL_ID_PROPERTY = "materialId";
    public static final String NAME_PROPERTY = "name";
    public static final String TYPE_RESERVED_PROPERTY = "typeReserved";


    public void setFile(String file) {
        writeProperty("file", file);
    }
    public String getFile() {
        return (String)readProperty("file");
    }

    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setMaterialId(Double materialId) {
        writeProperty("materialId", materialId);
    }
    public Double getMaterialId() {
        return (Double)readProperty("materialId");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setTypeReserved(String typeReserved) {
        writeProperty("typeReserved", typeReserved);
    }
    public String getTypeReserved() {
        return (String)readProperty("typeReserved");
    }

}
