package net.form105.db.cayenne.mapping.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Material was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Material extends CayenneDataObject {

    public static final String ADDITIONAL_INFORMATION_PROPERTY = "additionalInformation";
    public static final String BINDING_TYPE_ID_PROPERTY = "bindingTypeId";
    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String EPAC_PART_NUMBER_PROPERTY = "epacPartNumber";
    public static final String FINAL_SIZE_ID_PROPERTY = "finalSizeId";
    public static final String ID_PROPERTY = "id";
    public static final String MAXIMUM_QUANTITY_LEVEL_PROPERTY = "maximumQuantityLevel";
    public static final String MINIMUM_QUANTITY_LEVEL_PROPERTY = "minimumQuantityLevel";
    public static final String MODIFICATION_DATE_PROPERTY = "modificationDate";
    public static final String PAGE_COUNT_PROPERTY = "pageCount";
    public static final String PART_NUMBER_PROPERTY = "partNumber";
    public static final String PRICE_PROPERTY = "price";
    public static final String PRINT_ON_DEMAND_PROPERTY = "printOnDemand";
    public static final String QUANTITY_PROPERTY = "quantity";
    public static final String STAND_ALONE_PROPERTY = "standAlone";
    public static final String STATUS_PROPERTY = "status";
    public static final String TABS_PROPERTY = "tabs";
    public static final String TEXT_PAGE_COUNT_PROPERTY = "textPageCount";
    public static final String TITLE_PROPERTY = "title";
    public static final String TYPE_ID_PROPERTY = "typeId";


    public void setAdditionalInformation(String additionalInformation) {
        writeProperty("additionalInformation", additionalInformation);
    }
    public String getAdditionalInformation() {
        return (String)readProperty("additionalInformation");
    }

    public void setBindingTypeId(Double bindingTypeId) {
        writeProperty("bindingTypeId", bindingTypeId);
    }
    public Double getBindingTypeId() {
        return (Double)readProperty("bindingTypeId");
    }

    public void setCreationDate(Date creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty("creationDate");
    }

    public void setEpacPartNumber(String epacPartNumber) {
        writeProperty("epacPartNumber", epacPartNumber);
    }
    public String getEpacPartNumber() {
        return (String)readProperty("epacPartNumber");
    }

    public void setFinalSizeId(Double finalSizeId) {
        writeProperty("finalSizeId", finalSizeId);
    }
    public Double getFinalSizeId() {
        return (Double)readProperty("finalSizeId");
    }

    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setMaximumQuantityLevel(Double maximumQuantityLevel) {
        writeProperty("maximumQuantityLevel", maximumQuantityLevel);
    }
    public Double getMaximumQuantityLevel() {
        return (Double)readProperty("maximumQuantityLevel");
    }

    public void setMinimumQuantityLevel(Double minimumQuantityLevel) {
        writeProperty("minimumQuantityLevel", minimumQuantityLevel);
    }
    public Double getMinimumQuantityLevel() {
        return (Double)readProperty("minimumQuantityLevel");
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty("modificationDate", modificationDate);
    }
    public Date getModificationDate() {
        return (Date)readProperty("modificationDate");
    }

    public void setPageCount(Double pageCount) {
        writeProperty("pageCount", pageCount);
    }
    public Double getPageCount() {
        return (Double)readProperty("pageCount");
    }

    public void setPartNumber(String partNumber) {
        writeProperty("partNumber", partNumber);
    }
    public String getPartNumber() {
        return (String)readProperty("partNumber");
    }

    public void setPrice(Double price) {
        writeProperty("price", price);
    }
    public Double getPrice() {
        return (Double)readProperty("price");
    }

    public void setPrintOnDemand(String printOnDemand) {
        writeProperty("printOnDemand", printOnDemand);
    }
    public String getPrintOnDemand() {
        return (String)readProperty("printOnDemand");
    }

    public void setQuantity(Double quantity) {
        writeProperty("quantity", quantity);
    }
    public Double getQuantity() {
        return (Double)readProperty("quantity");
    }

    public void setStandAlone(String standAlone) {
        writeProperty("standAlone", standAlone);
    }
    public String getStandAlone() {
        return (String)readProperty("standAlone");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setTabs(String tabs) {
        writeProperty("tabs", tabs);
    }
    public String getTabs() {
        return (String)readProperty("tabs");
    }

    public void setTextPageCount(Double textPageCount) {
        writeProperty("textPageCount", textPageCount);
    }
    public Double getTextPageCount() {
        return (Double)readProperty("textPageCount");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setTypeId(Double typeId) {
        writeProperty("typeId", typeId);
    }
    public Double getTypeId() {
        return (Double)readProperty("typeId");
    }

}
