package net.form105.db.cayenne.mapping.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _OrderForm was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderForm extends CayenneDataObject {

    public static final String BILLING_ADDRESS1_PROPERTY = "billingAddress1";
    public static final String BILLING_ADDRESS2_PROPERTY = "billingAddress2";
    public static final String BILLING_CITY_PROPERTY = "billingCity";
    public static final String BILLING_COMPANY_PROPERTY = "billingCompany";
    public static final String BILLING_COUNTRY_PROPERTY = "billingCountry";
    public static final String BILLING_EMAIL_PROPERTY = "billingEmail";
    public static final String BILLING_FIRSTNAME_PROPERTY = "billingFirstname";
    public static final String BILLING_LASTNAME_PROPERTY = "billingLastname";
    public static final String BILLING_NOTIFICATION_EMAIL_PROPERTY = "billingNotificationEmail";
    public static final String BILLING_PHONE_PROPERTY = "billingPhone";
    public static final String BILLING_STATE_PROPERTY = "billingState";
    public static final String BILLING_ZIP_PROPERTY = "billingZip";
    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DELIVERY_DATE_PROPERTY = "deliveryDate";
    public static final String EPAC_ORDER_ID_PROPERTY = "epacOrderId";
    public static final String INVOICE_FILE_PROPERTY = "invoiceFile";
    public static final String INVOICE_NUMBER_PROPERTY = "invoiceNumber";
    public static final String INVOICE_STATUS_PROPERTY = "invoiceStatus";
    public static final String ORDER_ID_PROPERTY = "orderId";
    public static final String ORDER_REFERENCE_PROPERTY = "orderReference";
    public static final String SHIPPING_ADDRESS1_PROPERTY = "shippingAddress1";
    public static final String SHIPPING_ADDRESS2_PROPERTY = "shippingAddress2";
    public static final String SHIPPING_CITY_PROPERTY = "shippingCity";
    public static final String SHIPPING_COMPANY_PROPERTY = "shippingCompany";
    public static final String SHIPPING_COST_PROPERTY = "shippingCost";
    public static final String SHIPPING_COUNTRY_PROPERTY = "shippingCountry";
    public static final String SHIPPING_EMAIL_PROPERTY = "shippingEmail";
    public static final String SHIPPING_FIRSTNAME_PROPERTY = "shippingFirstname";
    public static final String SHIPPING_LASTNAME_PROPERTY = "shippingLastname";
    public static final String SHIPPING_NOTIFICATION_EMAIL_PROPERTY = "shippingNotificationEmail";
    public static final String SHIPPING_PHONE_PROPERTY = "shippingPhone";
    public static final String SHIPPING_STATE_PROPERTY = "shippingState";
    public static final String SHIPPING_ZIP_PROPERTY = "shippingZip";
    public static final String SPECIAL_INSTRUCTIONS_PROPERTY = "specialInstructions";
    public static final String STATUS_PROPERTY = "status";
    public static final String SUBTOTAL_PROPERTY = "subtotal";
    public static final String TAX_PROPERTY = "tax";
    public static final String TOTAL_PROPERTY = "total";
    public static final String TRACKING_NUMBER_PROPERTY = "trackingNumber";
    public static final String WORKSHOP_ID_PROPERTY = "workshopId";


    public void setBillingAddress1(String billingAddress1) {
        writeProperty("billingAddress1", billingAddress1);
    }
    public String getBillingAddress1() {
        return (String)readProperty("billingAddress1");
    }

    public void setBillingAddress2(String billingAddress2) {
        writeProperty("billingAddress2", billingAddress2);
    }
    public String getBillingAddress2() {
        return (String)readProperty("billingAddress2");
    }

    public void setBillingCity(String billingCity) {
        writeProperty("billingCity", billingCity);
    }
    public String getBillingCity() {
        return (String)readProperty("billingCity");
    }

    public void setBillingCompany(String billingCompany) {
        writeProperty("billingCompany", billingCompany);
    }
    public String getBillingCompany() {
        return (String)readProperty("billingCompany");
    }

    public void setBillingCountry(String billingCountry) {
        writeProperty("billingCountry", billingCountry);
    }
    public String getBillingCountry() {
        return (String)readProperty("billingCountry");
    }

    public void setBillingEmail(String billingEmail) {
        writeProperty("billingEmail", billingEmail);
    }
    public String getBillingEmail() {
        return (String)readProperty("billingEmail");
    }

    public void setBillingFirstname(String billingFirstname) {
        writeProperty("billingFirstname", billingFirstname);
    }
    public String getBillingFirstname() {
        return (String)readProperty("billingFirstname");
    }

    public void setBillingLastname(String billingLastname) {
        writeProperty("billingLastname", billingLastname);
    }
    public String getBillingLastname() {
        return (String)readProperty("billingLastname");
    }

    public void setBillingNotificationEmail(String billingNotificationEmail) {
        writeProperty("billingNotificationEmail", billingNotificationEmail);
    }
    public String getBillingNotificationEmail() {
        return (String)readProperty("billingNotificationEmail");
    }

    public void setBillingPhone(String billingPhone) {
        writeProperty("billingPhone", billingPhone);
    }
    public String getBillingPhone() {
        return (String)readProperty("billingPhone");
    }

    public void setBillingState(String billingState) {
        writeProperty("billingState", billingState);
    }
    public String getBillingState() {
        return (String)readProperty("billingState");
    }

    public void setBillingZip(String billingZip) {
        writeProperty("billingZip", billingZip);
    }
    public String getBillingZip() {
        return (String)readProperty("billingZip");
    }

    public void setCreationDate(Date creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty("creationDate");
    }

    public void setDeliveryDate(Date deliveryDate) {
        writeProperty("deliveryDate", deliveryDate);
    }
    public Date getDeliveryDate() {
        return (Date)readProperty("deliveryDate");
    }

    public void setEpacOrderId(String epacOrderId) {
        writeProperty("epacOrderId", epacOrderId);
    }
    public String getEpacOrderId() {
        return (String)readProperty("epacOrderId");
    }

    public void setInvoiceFile(String invoiceFile) {
        writeProperty("invoiceFile", invoiceFile);
    }
    public String getInvoiceFile() {
        return (String)readProperty("invoiceFile");
    }

    public void setInvoiceNumber(String invoiceNumber) {
        writeProperty("invoiceNumber", invoiceNumber);
    }
    public String getInvoiceNumber() {
        return (String)readProperty("invoiceNumber");
    }

    public void setInvoiceStatus(String invoiceStatus) {
        writeProperty("invoiceStatus", invoiceStatus);
    }
    public String getInvoiceStatus() {
        return (String)readProperty("invoiceStatus");
    }

    public void setOrderId(String orderId) {
        writeProperty("orderId", orderId);
    }
    public String getOrderId() {
        return (String)readProperty("orderId");
    }

    public void setOrderReference(String orderReference) {
        writeProperty("orderReference", orderReference);
    }
    public String getOrderReference() {
        return (String)readProperty("orderReference");
    }

    public void setShippingAddress1(String shippingAddress1) {
        writeProperty("shippingAddress1", shippingAddress1);
    }
    public String getShippingAddress1() {
        return (String)readProperty("shippingAddress1");
    }

    public void setShippingAddress2(String shippingAddress2) {
        writeProperty("shippingAddress2", shippingAddress2);
    }
    public String getShippingAddress2() {
        return (String)readProperty("shippingAddress2");
    }

    public void setShippingCity(String shippingCity) {
        writeProperty("shippingCity", shippingCity);
    }
    public String getShippingCity() {
        return (String)readProperty("shippingCity");
    }

    public void setShippingCompany(String shippingCompany) {
        writeProperty("shippingCompany", shippingCompany);
    }
    public String getShippingCompany() {
        return (String)readProperty("shippingCompany");
    }

    public void setShippingCost(Double shippingCost) {
        writeProperty("shippingCost", shippingCost);
    }
    public Double getShippingCost() {
        return (Double)readProperty("shippingCost");
    }

    public void setShippingCountry(String shippingCountry) {
        writeProperty("shippingCountry", shippingCountry);
    }
    public String getShippingCountry() {
        return (String)readProperty("shippingCountry");
    }

    public void setShippingEmail(String shippingEmail) {
        writeProperty("shippingEmail", shippingEmail);
    }
    public String getShippingEmail() {
        return (String)readProperty("shippingEmail");
    }

    public void setShippingFirstname(String shippingFirstname) {
        writeProperty("shippingFirstname", shippingFirstname);
    }
    public String getShippingFirstname() {
        return (String)readProperty("shippingFirstname");
    }

    public void setShippingLastname(String shippingLastname) {
        writeProperty("shippingLastname", shippingLastname);
    }
    public String getShippingLastname() {
        return (String)readProperty("shippingLastname");
    }

    public void setShippingNotificationEmail(String shippingNotificationEmail) {
        writeProperty("shippingNotificationEmail", shippingNotificationEmail);
    }
    public String getShippingNotificationEmail() {
        return (String)readProperty("shippingNotificationEmail");
    }

    public void setShippingPhone(String shippingPhone) {
        writeProperty("shippingPhone", shippingPhone);
    }
    public String getShippingPhone() {
        return (String)readProperty("shippingPhone");
    }

    public void setShippingState(String shippingState) {
        writeProperty("shippingState", shippingState);
    }
    public String getShippingState() {
        return (String)readProperty("shippingState");
    }

    public void setShippingZip(String shippingZip) {
        writeProperty("shippingZip", shippingZip);
    }
    public String getShippingZip() {
        return (String)readProperty("shippingZip");
    }

    public void setSpecialInstructions(String specialInstructions) {
        writeProperty("specialInstructions", specialInstructions);
    }
    public String getSpecialInstructions() {
        return (String)readProperty("specialInstructions");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setSubtotal(Double subtotal) {
        writeProperty("subtotal", subtotal);
    }
    public Double getSubtotal() {
        return (Double)readProperty("subtotal");
    }

    public void setTax(Double tax) {
        writeProperty("tax", tax);
    }
    public Double getTax() {
        return (Double)readProperty("tax");
    }

    public void setTotal(Double total) {
        writeProperty("total", total);
    }
    public Double getTotal() {
        return (Double)readProperty("total");
    }

    public void setTrackingNumber(String trackingNumber) {
        writeProperty("trackingNumber", trackingNumber);
    }
    public String getTrackingNumber() {
        return (String)readProperty("trackingNumber");
    }

    public void setWorkshopId(Double workshopId) {
        writeProperty("workshopId", workshopId);
    }
    public Double getWorkshopId() {
        return (Double)readProperty("workshopId");
    }

}
