package net.form105.db.cayenne.mapping.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _OrderItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderItem extends CayenneDataObject {

    public static final String EPAC_PART_NUMBER_PROPERTY = "epacPartNumber";
    public static final String MATERIAL_ID_PROPERTY = "materialId";
    public static final String MATERIAL_TITLE_PROPERTY = "materialTitle";
    public static final String ORDER_ID_PROPERTY = "orderId";
    public static final String PART_NUMBER_PROPERTY = "partNumber";
    public static final String PRICE_PROPERTY = "price";
    public static final String QUANTITY_PROPERTY = "quantity";
    public static final String TYPE_RESERVED_PROPERTY = "typeReserved";


    public void setEpacPartNumber(String epacPartNumber) {
        writeProperty("epacPartNumber", epacPartNumber);
    }
    public String getEpacPartNumber() {
        return (String)readProperty("epacPartNumber");
    }

    public void setMaterialId(Double materialId) {
        writeProperty("materialId", materialId);
    }
    public Double getMaterialId() {
        return (Double)readProperty("materialId");
    }

    public void setMaterialTitle(String materialTitle) {
        writeProperty("materialTitle", materialTitle);
    }
    public String getMaterialTitle() {
        return (String)readProperty("materialTitle");
    }

    public void setOrderId(String orderId) {
        writeProperty("orderId", orderId);
    }
    public String getOrderId() {
        return (String)readProperty("orderId");
    }

    public void setPartNumber(String partNumber) {
        writeProperty("partNumber", partNumber);
    }
    public String getPartNumber() {
        return (String)readProperty("partNumber");
    }

    public void setPrice(Double price) {
        writeProperty("price", price);
    }
    public Double getPrice() {
        return (Double)readProperty("price");
    }

    public void setQuantity(Double quantity) {
        writeProperty("quantity", quantity);
    }
    public Double getQuantity() {
        return (Double)readProperty("quantity");
    }

    public void setTypeReserved(String typeReserved) {
        writeProperty("typeReserved", typeReserved);
    }
    public String getTypeReserved() {
        return (String)readProperty("typeReserved");
    }

}
