package net.form105.db.cayenne.mapping.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _SessionUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SessionUser extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String SESSION_ID_PROPERTY = "sessionId";
    public static final String TIME_STAMP_PROPERTY = "timeStamp";
    public static final String USER_ID_PROPERTY = "userId";


    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setSessionId(String sessionId) {
        writeProperty("sessionId", sessionId);
    }
    public String getSessionId() {
        return (String)readProperty("sessionId");
    }

    public void setTimeStamp(Date timeStamp) {
        writeProperty("timeStamp", timeStamp);
    }
    public Date getTimeStamp() {
        return (Date)readProperty("timeStamp");
    }

    public void setUserId(Double userId) {
        writeProperty("userId", userId);
    }
    public Double getUserId() {
        return (Double)readProperty("userId");
    }

}
