package net.form105.db.cayenne.mapping.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _State was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _State extends CayenneDataObject {

    public static final String ABBREVIATION_PROPERTY = "abbreviation";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";


    public void setAbbreviation(String abbreviation) {
        writeProperty("abbreviation", abbreviation);
    }
    public String getAbbreviation() {
        return (String)readProperty("abbreviation");
    }

    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

}
