package net.form105.db.cayenne.mapping.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Tax was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tax extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String TOTAL_SALES_TAX_PROPERTY = "totalSalesTax";
    public static final String ZIP_PROPERTY = "zip";


    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setTotalSalesTax(Double totalSalesTax) {
        writeProperty("totalSalesTax", totalSalesTax);
    }
    public Double getTotalSalesTax() {
        return (Double)readProperty("totalSalesTax");
    }

    public void setZip(String zip) {
        writeProperty("zip", zip);
    }
    public String getZip() {
        return (String)readProperty("zip");
    }

}
