package net.form105.db.cayenne.mapping.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _UserGroupAccess was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserGroupAccess extends CayenneDataObject {

    public static final String GROUP_ID_PROPERTY = "groupId";
    public static final String USER_ID_PROPERTY = "userId";


    public void setGroupId(Double groupId) {
        writeProperty("groupId", groupId);
    }
    public Double getGroupId() {
        return (Double)readProperty("groupId");
    }

    public void setUserId(Double userId) {
        writeProperty("userId", userId);
    }
    public Double getUserId() {
        return (Double)readProperty("userId");
    }

}
