package net.form105.db.cayenne.mapping.auto;

import java.util.Date;
import java.util.List;

import net.form105.db.cayenne.mapping.WorkshopMaterial;

import org.apache.cayenne.CayenneDataObject;


/**
 * Class _Workshop was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Workshop extends CayenneDataObject {

    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String ID_PROPERTY = "id";
    public static final String MODIFICATION_DATE_PROPERTY = "modificationDate";
    public static final String NAME_PROPERTY = "name";
    public static final String STATUS_PROPERTY = "status";
    public static final String TO_WORKSHOP_MATERIAL_PROPERTY = "toWorkshopMaterial";

    public static final String ID_PK_COLUMN = "id";

    public void setCreationDate(Date creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty("creationDate");
    }

    public void setId(Double id) {
        writeProperty("id", id);
    }
    public Double getId() {
        return (Double)readProperty("id");
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty("modificationDate", modificationDate);
    }
    public Date getModificationDate() {
        return (Date)readProperty("modificationDate");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void addToToWorkshopMaterial(WorkshopMaterial obj) {
        addToManyTarget("toWorkshopMaterial", obj, true);
    }
    public void removeFromToWorkshopMaterial(WorkshopMaterial obj) {
        removeToManyTarget("toWorkshopMaterial", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WorkshopMaterial> getToWorkshopMaterial() {
        return (List<WorkshopMaterial>)readProperty("toWorkshopMaterial");
    }


}
