package net.form105.db.cayenne.mapping.auto;

import net.form105.db.cayenne.mapping.Workshop;

import org.apache.cayenne.CayenneDataObject;


/**
 * Class _WorkshopMaterial was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WorkshopMaterial extends CayenneDataObject {

    public static final String MATERIAL_ID_PROPERTY = "materialId";
    public static final String POSITION_RESERVED_PROPERTY = "positionReserved";
    public static final String WORKSHOP_MATERIAL_REV_ARRAY_PROPERTY = "workshopMaterialRevArray";

    public static final String WORKSHOP_ID_PK_COLUMN = "workshop_id";

    public void setMaterialId(Double materialId) {
        writeProperty("materialId", materialId);
    }
    public Double getMaterialId() {
        return (Double)readProperty("materialId");
    }

    public void setPositionReserved(Double positionReserved) {
        writeProperty("positionReserved", positionReserved);
    }
    public Double getPositionReserved() {
        return (Double)readProperty("positionReserved");
    }

    public void setWorkshopMaterialRevArray(Workshop workshopMaterialRevArray) {
        setToOneTarget("workshopMaterialRevArray", workshopMaterialRevArray, true);
    }

    public Workshop getWorkshopMaterialRevArray() {
        return (Workshop)readProperty("workshopMaterialRevArray");
    }


}
