package net.form105.rm.server.model.auto;

/** Class _Customer was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Customer extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATION_DATE_PROPERTY = "creation_Date";
    public static final String CREATION_TIME_PROPERTY = "creation_Time";
    public static final String CREATOR_PROPERTY = "creator";
    public static final String CUSTOMER_POUND_PROPERTY = "customer_pound";
    public static final String MAX_SHIP_WEIGHT_PROPERTY = "max_Ship_Weight";
    public static final String MODIFIER_PROPERTY = "modifier";
    public static final String RESALE_ID_PROPERTY = "resale_ID";
    public static final String SALESPERSON_POUND_PROPERTY = "salesperson_pound";

    public static final String CUSTOMER_POUND_PK_COLUMN = "Customer #";

    public void setCreation_Date(java.util.Date creation_Date) {
        writeProperty("creation_Date", creation_Date);
    }
    public java.util.Date getCreation_Date() {
        return (java.util.Date)readProperty("creation_Date");
    }
    
    
    public void setCreation_Time(java.util.Date creation_Time) {
        writeProperty("creation_Time", creation_Time);
    }
    public java.util.Date getCreation_Time() {
        return (java.util.Date)readProperty("creation_Time");
    }
    
    
    public void setCreator(String creator) {
        writeProperty("creator", creator);
    }
    public String getCreator() {
        return (String)readProperty("creator");
    }
    
    
    public void setCustomer_pound(String customer_pound) {
        writeProperty("customer_pound", customer_pound);
    }
    public String getCustomer_pound() {
        return (String)readProperty("customer_pound");
    }
    
    
    public void setMax_Ship_Weight(Double max_Ship_Weight) {
        writeProperty("max_Ship_Weight", max_Ship_Weight);
    }
    public Double getMax_Ship_Weight() {
        return (Double)readProperty("max_Ship_Weight");
    }
    
    
    public void setModifier(String modifier) {
        writeProperty("modifier", modifier);
    }
    public String getModifier() {
        return (String)readProperty("modifier");
    }
    
    
    public void setResale_ID(String resale_ID) {
        writeProperty("resale_ID", resale_ID);
    }
    public String getResale_ID() {
        return (String)readProperty("resale_ID");
    }
    
    
    public void setSalesperson_pound(String salesperson_pound) {
        writeProperty("salesperson_pound", salesperson_pound);
    }
    public String getSalesperson_pound() {
        return (String)readProperty("salesperson_pound");
    }
    
    
}
