package net.form105.rm.server.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Customers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Customers extends CayenneDataObject {

    public static final String CREATOR_PROPERTY = "creator";

    public static final String MODIFIER_PK_COLUMN = "Modifier";

    public void setCreator(String creator) {
        writeProperty("creator", creator);
    }
    public String getCreator() {
        return (String)readProperty("creator");
    }

}
