package net.form105.rm.server.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ResourceElement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ResourceElement extends CayenneDataObject {

    public static final String ELEMENT_ID_PROPERTY = "elementId";
    public static final String ELEMENT_NAME_PROPERTY = "elementName";
    public static final String ELEMENT_TYPE_PROPERTY = "elementType";

    public static final String OBJECT_ID_PK_COLUMN = "objectId";

    public void setElementId(String elementId) {
        writeProperty("elementId", elementId);
    }
    public String getElementId() {
        return (String)readProperty("elementId");
    }

    public void setElementName(String elementName) {
        writeProperty("elementName", elementName);
    }
    public String getElementName() {
        return (String)readProperty("elementName");
    }

    public void setElementType(String elementType) {
        writeProperty("elementType", elementType);
    }
    public String getElementType() {
        return (String)readProperty("elementType");
    }

}
